### ISSUE TITLE
explore dynamic usage of BMI2 instructions

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/bn256#11]
The current implementation determines at compile time whether to use BMI2 instructions at runtime _based on the CPU building the software_. This can result in the software using illegal instructions when being built on one CPU and then copied over and ran on another CPU (such as when building binary packages for broad consumption, for example).

I would say this "`-march=native`-like" behavior is generally undesirable as default; especially in a library intended for broad usage as bn256 is. If BMI2 instructions make a noticeable improvement in the performance of the software they should be enabled at runtime only if the CPU supports them.

Speaking more specifically to Leap, there are a couple of additional reasons to avoid this behavior:

Desktop CPUs without BMI2 were still, as far as I'm aware, shipping as of a year ago. AFAIK Pentiums & Celerons pre-Alder Lake (2021) lack BMI2 instructions (as they also similarly lack AVX2). I can at least confirm firsthand that a Pentium G4400 (Skylake, 2015) is lacking BMI2 instructions, and a Pentium G5400 (Coffee Lake, 2018) [appears to lack BMI2 too](https://review.kakaku.com/review/K0001045053/ReviewCD=1277098/ImageID=490285/). These CPUs are completely capable of validating all public Antelope chains, including supporting 128GB of memory for something like WAX. These two examples even support ECC memory! I do not believe Antelope's binaries should fail to support CPUs released only a year or two ago when those CPUs are fully capable of validating all public Antelope chains.

And even if we did decide it's okay for Leap binaries to require BMI2, the entirety of Leap should be built with AVX2 etc so the entirety of Leap can use and benefit from more recent instructions. Thus again, a small library should not be making this decision on its own, but rather the application using the library.

**Comment by stephenpdiesel** [comment]
Holding off for this iteration until HM returns in Feb for further discussion
