### ISSUE TITLE
Missing header "nonstd/span.hpp"

### ISSUE THREAD

**Issue by nathanielhourt** [AntelopeIO/bn256#13]
In the `bn256/span.h` header at [line 7](https://github.com/AntelopeIO/bn256/blob/4fe51c043d86798fa9bab7015e4d48d1722a9fa5/include/bn256/span.h#L7), used when the standard library `span` header is not available, which it should never be since the `CMakeLists.txt` sets the C++ version to 17, it instead tries to use a "nonstd/span.hpp", but that file doesn't seem to be anywhere and so the build fails.

How should I get this file? =)

**Comment by heifner** [comment]
@huangminghuang

**Comment by huangminghuang** [comment]
> How should I get this file? =)

git submodule update --recursive --init

**Comment by nathanielhourt** [comment]
D'oh! Out of sync submodules strike again! I forgot to use `--init` when I updated. Oops. =)
